### ISSUE TITLE
Support large file encryption?

### ISSUE THREAD

**Issue by pyy** [andrewcooke/simple-crypt#10]
Hello,

May I ask how can I use simple-crypt to encrypt  large file (like 2G, 3G) ? 
Will it get error about RAM for such big file?

Thank you.

**Comment by andrewcooke** [comment]
that depends on your computer, our OS, and python.  the simplest way would be to try it and see.

simple-crypt does require that the entire data to be encrypted is in memory.  i did try to extend the program to avoid this, but couldn't find a way to do that which kept a simple interface (see the final "Warning" on the main page).

**Comment by andrewcooke** [comment]
thinking some more, i don't see a problem with doing this in two passes.  i'll keep this issue open until i've thought some more.

**Comment by andrewcooke-isti** [comment]
this is discussed at https://www.ietf.org/mail-archive/web/cfrg/current/msg07496.html if i understand correctly

**Comment by pyy** [comment]
Hello, Andrew, thank you for your kindly help.

I have to say I'm not good at the encryption algorithm. I'm not clear about the idea of this article says, it looks put the symbols before and after each trunk, if I understand correctly.

For the RAM problem, I don't think reading all the data into the RAM together is a good way. It cost time and resources of the computer, especially for the small RAM facilities I use, like RaspberryPi.

I really hope you can fix this problem, if you like.

Last but not least, I am really appropriated for your reply and helps!

**Comment by andrewcooke** [comment]
after reading the thread i linked to above again, i'm going to close this without doing anything.  hopefully one day, when there is a standard, i can either add it here or make a new, more flexible library.

**Comment by rsyring** [comment]
FWIW, I would like to see something like this provided in simple-crypt or a different library.  It's obviously hard to get the problem solved correctly, which lends itself to the need for someone who really understands what it going on to lay the foundation.  

Even though the API might not be super simple (as it is currently), IMO, it a slightly more complex API to support a much more complex problem is still a win.

**Comment by andrewcooke** [comment]
have you looked at google's keyczar?  it used to be python 2 only (which is partly why i wrote simple-crypt).  it has a different approach, using a key repository, which is a bit more complicated to use, but should be more efficient.

i had a look and can't tell if it now works on python 3.  if you use it and it does, please can you tell me and i'll add it to the "alternatives" section in the readme.

https://pypi.python.org/pypi/python-keyczar

**Comment by rsyring** [comment]
I did actually, based on the suggestion in your readme.  Python 3 support is close, but hasn't got any love recently:

https://github.com/google/keyczar/issues/125

**Comment by andrewcooke** [comment]
:(  sorry.  in that case, python-aead?  https://github.com/Ayrx/python-aead  just ignore the associated data.

**Comment by rsyring** [comment]
So you are saying that I could just use the encrypt method on that library on chunks of an input file?

That is basically what I am doing by following the instructions here: http://eli.thegreenplace.net/2010/06/25/aes-encryption-of-files-in-python-with-pycrypto/

I'm not sure I know enough about encryption to know which method would be better.

**Comment by andrewcooke** [comment]
i think you should read the whole file into memory and then call `encrypt(data)`.  don't do chunks (looking at the code, there's an `_encrypt_from_parts` that *might* do chunks, but you'd need to understand the iv parameter and how it's used and i don't see any docs and am not going to guess).

**Comment by andrewcooke** [comment]
also eli is a smart guy, so his instructions are likely correct, but calling pycrypto directly is complicated and easy to get wrong so be very careful if you follow his addvice.

**Comment by andrewcooke** [comment]
ARRRGH.  i'm sorry - i thought this was (one of the many threads) about speed, not large file sizes.  in that case i guess you'll have to follow eli's blog.
