### ISSUE TITLE
is there a way decrypt encrypted text in java?

### ISSUE THREAD

**Issue by onurakman** [andrewcooke/simple-crypt#11]
is there a way decrypt encrypted text in java?

**Comment by andrewcooke** [comment]
there's no library i know of, but someone who understood cryptography in java could certainly write one - it's all just standard algorithms.

**Comment by andrewcooke** [comment]
would this be useful to you?  i could try to write it, but i have a bunch of other things that need doing.  can you give me some idea of how important it would be?

**Comment by onurakman** [comment]
yes it would but may be only for me :)
