### ISSUE TITLE
Encryption/Decryption is very slow

### ISSUE THREAD

**Issue by erfaan** [andrewcooke/simple-crypt#13]
I use an alphanumeric key of size 8 to encrypt a 120 char long base64 encoded string. The encryption and decryption take 3-5 seconds. This is too slow for any real time application.

**Comment by andrewcooke** [comment]
if it is too slow for you then i suspect you will need to use something else, sorry.

the reason that simple-encrypt is slow is that it uses a PBKDF to help make "poor" passwords more secure.  in short, anyone trying to guess your password will also need to spend 3-5 second per guess.

this is acceptable (imho) when used just once or twice by a program (eg to read or save some results in an encrypted way).  if you need something that does many encryptions / decryptions every time your program runs then you probably need to use a different library.

sorry - that's just the trade-off in involved.  simple-crypt tries to be safe, perhaps at the expense of being efficient.

**Comment by andrewcooke** [comment]
you're not the first person to raise an issue about this, so i've added an explanation to the front page - https://github.com/andrewcooke/simple-crypt#speed
