### ISSUE TITLE
Ability to derive keys only once for multiple decrypts

### ISSUE THREAD

**Issue by mideeks** [andrewcooke/simple-crypt#14]
Right now the keys are derived from scratch every single time decrypt is called. I have a lot of values that have been encrypted with the same password that I want to decrypt in bulk (config files with individual values encrypted). Right now it takes over a minute to decrypt about 20 secrets and it appears most of the time is spent here:
```
  File "/usr/local/lib/python2.7/site-packages/simplecrypt/__init__.py", line 127, in _expand_keys
    keys = _pbkdf2(_str_to_bytes(password), salt, 2*key_len, expansion_count)
```

Is this something you could add? Or like your description says should I just use something else if I want this feature?

**Comment by andrewcooke** [comment]
yeah, i'm afraid you'll need to use something else.  this library is designed to do just one thing well and you're asking it to do something different.  sorry.

**Comment by trein** [comment]
@mideeks You can speed up the computation by choosing weaker encryption settings (if that is an option). That can be done by changing `LATEST` variable here: https://github.com/andrewcooke/simple-crypt/blob/master/src/simplecrypt/__init__.py#L16. I believe @andrewcooke could help letting us know if he has something planned regarding allowing configuration of encryption parameters.

**Comment by andrewcooke** [comment]
simple-crypt is intended to be a library that is very hard to use incorrectly.  so it does not (and will not) expose parameters.

changing LATEST gives you older routines that are not as secure for various reasons.  it would be better to find a different library, honestly.

(sorry, but it really was intended to be "idiot proof" and that comes at a price.  also, i don't have the time or expertise to tweak things).

**Comment by mideeks** [comment]
Thanks @andrewcooke I understand. For those who end up here wondering the same thing, you can find an alternative here if you really need it like I did:
https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet
