### ISSUE TITLE
'utf-8' codec can't decode byte 0xa6 in position 7: invalid start byte

### ISSUE THREAD

**Issue by rohitkhatri** [andrewcooke/simple-crypt#16]
I'm getting this error while encoding:

    'utf-8' codec can't decode byte 0xa6 in position 7: invalid start byte

**Comment by colinstreicher** [comment]
This is due to your data not being in UTF-8. Can you attach a small file that causes this error? I may be able to write a small patch for it.

**Comment by rohitkhatri** [comment]
Solved it already, thanks

**Comment by andrewcooke** [comment]
thanks colin.  will close this.
