### ISSUE TITLE
getting incorrect password when im typing the same thing

### ISSUE THREAD

**Issue by JosephMeli** [andrewcooke/simple-crypt#18]
File "/usr/local/lib/python2.7/dist-packages/simplecrypt/__init__.py", line 72, in decrypt
    _assert_hmac(hmac_key, hmac, hmac2)
  File "/usr/local/lib/python2.7/dist-packages/simplecrypt/__init__.py", line 116, in _assert_hmac
    raise DecryptionException('Bad password or corrupt / modified data.')
simplecrypt.DecryptionException: Bad password or corrupt / modified data.

**Comment by andrewcooke** [comment]
There's most likely a problem with your code.  Have you got the arguments to the functions the right way round?

**Comment by JosephMeli** [comment]
no it was a problem with how I installed it. I uninstalled the library and re-installed then it worked with nothing else changed

**Comment by andrewcooke** [comment]
huh.  weird.  thanks for the follow-up.
