### ISSUE TITLE
Code audits and security

### ISSUE THREAD

**Issue by selfus** [andrewcooke/simple-crypt#19]
Hello,

I have project where I would like to use simple-crypt, and I am wondering how safe to use it is, and if there has been any code security audits before.

Thanks

**Comment by andrewcooke** [comment]
hi, there have been NO audits apart from the informal discussions noted on the project front page.  sorry.

**Comment by selfus** [comment]
Thanks. I'll give it a try.

However, the Pypi version is from 2015. Will be updated anytime soon?

**Comment by andrewcooke** [comment]
none of the commits since then have altered the library code - https://github.com/andrewcooke/simple-crypt/commits/master

there won't be a new release unless there's some bug / change.

**Comment by andrewcooke** [comment]
none of the commits since then have altered the library code - https://github.com/andrewcooke/simple-crypt/commits/master

there won't be a new release unless there's some bug / change.

**Comment by andrewcooke** [comment]
i guess i could do a release to include the example.  but for now you can grab it from https://github.com/andrewcooke/simple-crypt/blob/master/src/simplecrypt/example-cmd.py
