### ISSUE TITLE
ImportError: No module named KDF

### ISSUE THREAD

**Issue by 4616** [andrewcooke/simple-crypt#4]
I tried to import encrypt and decrypt:

from simplecrypt import encrypt, decrypt

I get the following error:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from simplecrypt import encrypt, decrypt
  File "/usr/local/lib/python2.7/dist-packages/simplecrypt/**init**.py", line 4, in <module>
    from Crypto.Protocol.KDF import PBKDF2
ImportError: No module named KDF

**Comment by kidd0** [comment]
@andrewcooke : I am facing a similar issue. I have the same version which is shown above (2.6.1)
Is there anyway I can fix this?

**Comment by andrewcooke** [comment]
what os are you using?  what version of python?

**Comment by andrewcooke** [comment]
weird.  the comment above was via email, in response to an email i received.  i guess someone raised an issue and then deleted it.

**Comment by kidd0** [comment]
Hi,

I'm extremely sorry about the comment. I resolved the issue. Immensely
thankful for the prompt reply. Sorry once again.

**Comment by andrewcooke** [comment]
no problem - but what was the issue?  it might help me help someone else.

cheers,
andrew
