### ISSUE TITLE
Do not remove old versions from PyPi

### ISSUE THREAD

**Issue by hgross** [andrewcooke/simple-crypt#6]
With release 4.0 the old releases 3.x.x have been deleted from the PyPi index.
Old releases should not be removed from the index.

- Every other PyPi package using the 3.x.x version is now incompatible if another endpoint already upgraded to 4.0.0.
- If a user had a package installed which had the requirement `"simple-crypt>=3.0.2"` and installed  the same package today with the given requirement string, both sides are unable to communicate because 4.0 is not compatible with 3.x

If the old releases were still present, a requirement string "simple-crypt=3.0.2" could be used and everything would be fine. But now the users of packages with the simple-crypt requirement are forced to upgrade.
Please don't remove the old releases.

**Comment by andrewcooke** [comment]
hi - what on earth are you talking about?

**Comment by andrewcooke** [comment]
https://pypi.python.org/pypi/simple-crypt/3.0.0 for example

**Comment by andrewcooke** [comment]
or https://pypi.python.org/pypi/simple-crypt/3.0.2

**Comment by hgross** [comment]
Ahhh damn, my bad. I messed up my local conf and was on https://testpypi.python.org while trying to install simple-crypt 3.0.2 via pip, then instantly assumed it was removed -> wrong assumption, sorry.

**Comment by andrewcooke** [comment]
ok, no problem.  sorry for what looked like a short-tempered reply.  at first i had absolutely no idea what you were talking about as i've never paid much attention to old verions on pypi, so the original question was not sarcastic...
